lang = {
    "EN":{
        "home":"Home",
        "ProductName":"Product Name",
        "Weight":"Weight",
        "Price":"Price",
        "Details":"Details",
        "MyProfile":"My Profile",
        "ChangePassword":"Change Password",
        "LogOut":"Log Out",
        "BranchCode":"Branch Code",
        "Department":"Department",
        "UserName":"User Name",
        "Category":"Category",
        "Product":"Product",
        "CreateTransactions":"Create Transactions",
        "ReopenTransactions":"Reopen Transactions",
        "CloseTransactions":"Closed Transactions",
        "CopyRight":"Copyright National Bank of Cambodia. All Rights Reserved",
        "ConsumerPriceIndexSystem":"Consumer Price Index System",
        "Dashboard":"Dashboard",
        "Total":"Total",
        "Submitted":"Submitted",
        "Rejected":"Rejected",
        "Authorized":"Authorized",
        "Reopen":"Reopen",
        "Active":"Active",
        "Deactivated":"Deactivated",
        "Pending":"Pending",
        "Closed":"Closed",
        "Open":"Open",
        "Rejected By Authorizer":"Rejected By Authorizer",
        "Rejected By Checker":"Rejected By Checker",
        "Saved":"Saved",
        "Accepted":"Accepted",
        "InputterNoted":"Inputter Noted",
        "AuthorizerNoted":"Authorizer Noted",
        "CheckerNoted":"Checker Noted",
        "Rice":"Rice", 
        "Shipping":"Shipping", 
        "Ingredients":"Ingredients", 
        "Meat":"Meat", 
        "Fish and Seafood":"Fish and Seafood", 
        "Fruit":"Fruit", 
        "Vegetables":"Vegetables", 
        "Beverages and Tobacco":"Beverages and Tobacco", 
        "Restaurant":"Restaurant", 
        "Clothes and Shoes":"Clothes and Shoes", 
        "Medicine":"Medicine", 
        "Housing":"Housing", 
        "Rice Details":"Rice Details", 
        "Shipping Details":"Shipping Details", 
        "Ingredients Details":"Ingredients Details", 
        "Meat Details":"Meat Details", 
        "Fish and Seafood Details":"Fish and Seafood Details", 
        "Fruit Details":"Fruit Details", 
        "Vegetables Details":"Vegetables Details", 
        "Beverages and Tobacco Details":"Beverages and Tobacco Details", 
        "Restaurant Details":"Restaurant Details", 
        "Clothes and Shoes Details":"Clothes and Shoes Details", 
        "Medicine Details":"Medicine Details", 
        "Housing Details":"Housing Details",
        "Change User Password":"Change User Password",
        "Old Password":"Old Password",
        "Confirm Old Password":"Confirm Old Password",
        "New Password":"New Password",
        "Submit":"Submit",
        "Save":"Save",
        "Clear":"Clear",
        "User Setting":"User Setting",
        "Change Password":"Change Password",
        "Username":"User Name",
        "Role":"Role",
        "Inputter":"Inputter",
        "Authorizer":"Authorizer",
        "Checker":"Checker",
        "Administrator":"Administrator",
        "Overview":"Overview",
        "Edit Profile":"Edit Profile",
        "Profile Details":"Profile Details",
        "Full Name":"Full Name",
        "Gender":"Gender",
        "Department":"Department",
        "Position":"Position",
        "Email":"Email",
        "Languages":"Languages",
        "English":"English",
        "Khmer":"Khmer",
        "Female":"Female",
        "Male":"Male",
        "Save Changed":"Save Changed",
        "Submitted Transactions":"Submitted Transactions",
        "Submitted Transactions Management":"Submitted Transactions Management",
        "Transactions History":"Transactions History",
        "Transactions History Management":"Transactions History Management",
        "Status":"Status",
        "Number of Products":"Number of Products",
        "Date":"Date",
        "Food":"Food",
        "Authorized Transactions":"Authorized Transactions",
        "Authorized Transactions Management":"Authorized Transactions Management",
        "Checked Transactions":"Checked Transactions",
        "Checked Transactions Details":"Checked Transactions Details"
    },
    "KH":{
        "home":"ផ្ទះ",
        "ProductName":"ឈ្មោះផលិតផល",
        "Weight":"ទំងន់",
        "Price":"តំលៃ",
        "Details":"ព័ត៌មានលម្អិត",
        "MyProfile":"កម្រងព័ត៌មានអ្នកប្រើប្រាស់",
        "ChangePassword":"ផ្លាស់ប្តូរពាក្យសម្ងាត់",
        "LogOut":"ចាកចេញ",
        "BranchCode":"លេខកូដសាខា",
        "Department":"នាយកដ្ឋាន",
        "UserName":"ឈ្មោះ​អ្នកប្រើប្រាស់",
        "Category":"ប្រភេទ",
        "Product":"ផលិតផល",
        "CreateTransactions":"បង្កើតប្រតិបត្តិការ",
        "ReopenTransactions":"បើកប្រតិបត្តិការឡើងវិញ",
        "CloseTransactions":"បិទប្រតិបត្តិការ",
        "CopyRight":"រក្សាសិទ្ធិ ធនាគារជាតិនៃកម្ពុជា រក្សា​រ​សិទ្ធ​គ្រប់យ៉ាង",
        "ConsumerPriceIndexSystem":"ប្រព័ន្ធសន្ទស្សន៍តម្លៃអ្នកប្រើប្រាស់",
        "Dashboard":"ផ្ទាំងគ្រប់គ្រង",
        "Total":"សរុប",
        "Submitted":"បានដាក់ស្នើ",
        "Rejected":"បដិសេធ",
        "Authorized":"អនុញ្ញាត",
        "Reopen":"បើកឡើងវិញ",
        "Active":"ដំណើរការ",
        "Deactivated":"បិទដំណើរការ",
        "Pending":"កំពុងរង់ចាំ",
        "Closed":"បិទ",
        "Open":"បើក",
        "Rejected By Authorizer":"បដិសេធដោយអ្នកផ្តល់សិទ្ធិ",
        "Rejected By Checker":"ច្រានចោលដោយអ្នកពិនិត្យ",
        "Saved":"បានរក្សាទុក",
        "Accepted":"ទទួលយក",
        "InputterNoted":"ព័ត៌មានអ្នកបញ្ចូល",
        "AuthorizerNoted":"ព័ត៌មានអ្នកអនុញ្ញាត",
        "CheckerNoted":"ព័ត៌មានអ្នកពិនិត្យ",
        "Rice":"អង្ករ", 
        "Shipping":"ការដឹកជញ្ជូន", 
        "Ingredients":"គ្រឿងផ្សំ", 
        "Meat":"សាច់", 
        "Fish and Seafood":"ត្រី និងអាហារសមុទ្រ", 
        "Fruit":"ផ្លែឈើ", 
        "Vegetables":"បន្លែ", 
        "Beverages and Tobacco":"ភេសជ្ជៈ និងថ្នាំជក់", 
        "Restaurant":"ភោជនីយដ្ឋាន", 
        "Clothes and Shoes":"សម្លៀកបំពាក់និងស្បែកជើង", 
        "Medicine":"ថ្នាំ", 
        "Housing":"លំនៅដ្ឋាន",
        "Rice Details":"ព័ត៌មានលម្អិតអង្ករ", 
        "Shipping Details":"ព័ត៌មានលម្អិតការដឹកជញ្ជូន", 
        "Ingredients Details":"ព័ត៌មានលម្អិតគ្រឿងផ្សំ", 
        "Meat Details":"ព័ត៌មានលម្អិតសាច់", 
        "Fish and Seafood Details":"ព័ត៌មានលម្អិតត្រី និងអាហារសមុទ្រ", 
        "Fruit Details":"ព័ត៌មានលម្អិតផ្លែឈើ", 
        "Vegetables Details":"ព័ត៌មានលម្អិតបន្លែ", 
        "Beverages and Tobacco Details":"ព័ត៌មានលម្អិតភេសជ្ជៈ និងថ្នាំជក់", 
        "Restaurant Details":"ព័ត៌មានលម្អិតភោជនីយដ្ឋាន", 
        "Clothes and Shoes Details":"ព័ត៌មានលម្អិតសម្លៀកបំពាក់និងស្បែកជើង", 
        "Medicine Details":"ព័ត៌មានលម្អិតថ្នាំ", 
        "Housing Details":"ព័ត៌មានលម្អិតលំនៅដ្ឋាន",  
        "Change User Password":"ផ្លាស់ប្តូរពាក្យសម្ងាត់អ្នកប្រើប្រាស់",
        "Old Password":"លេខសំងាត់​ចាស់",
        "Confirm Old Password":"បញ្ជាក់ពាក្យសម្ងាត់ចាស់",
        "New Password":"ពាក្យសម្ងាត់​ថ្មី",
        "Submit":"ដាក់ស្នើ",
        "Save":"រក្សាទុក",
        "Clear":"សំអាត",
        "User Setting":"ការកំណត់អ្នកប្រើប្រាស់",
        "Change Password":"ផ្លាស់ប្តូរពាក្យសម្ងាត់",
        "User Profile":"កម្រងព័ត៌មានអ្នកប្រើប្រាស់",
        "Username":"ឈ្មោះ​អ្នកប្រើប្រាស់",
        "Role":"តួនាទី",
        "Inputter":"អ្នកបញ្ចូល",
        "Authorizer":"អ្នកអនុញ្ញាត",
        "Checker":"អ្នកត្រួតពិនិត្យ",
        "Administrator":"អ្នកគ្រប់គ្រង",
        "Overview":"ទិដ្ឋភាពទូទៅ",
        "Edit Profile":"កែសម្រួលប្រវត្តិរូប",
        "Profile Details":"ព័ត៌មានលំអិតអំពីប្រវត្តិរូប",
        "Full Name":"ឈ្មោះ​ពេញ",
        "Gender":"ភេទ",
        "Position":"មុខតំណែង",
        "Email":"អ៊ីមែល",
        "Languages":"ភាសា",
        "English":"ភាសាអង់គ្លេស",
        "Khmer":"ភាសាខ្មែរ",
        "Female":"ស្រី",
        "Male":"ប្រុស",
        "Save Changed":"រក្សាទុកបានផ្លាស់ប្តូរ",
        "Submitted Transactions":"ប្រតិបត្តិការដែលបានដាក់ស្នើ",
        "Submitted Transactions Management":"ការគ្រប់គ្រងប្រតិបត្តិការដែលបានបញ្ជូន",
        "Transactions History":"ប្រវត្តិប្រតិបត្តិការ",
        "Transactions History Management":"ការគ្រប់គ្រងប្រវត្តិប្រតិបត្តិការ",
        "Status":"ស្ថានភាព",
        "Number of Products":"ចំនួនផលិតផល",
        "Date":"កាលបរិច្ឆេទ",
        "Food":"អាហារ",
        "Authorized Transactions":"ប្រតិបត្តិការដែលមានការអនុញ្ញាត",
        "Authorized Transactions Management":"ការគ្រប់គ្រងប្រតិបត្តិការដែលមានការអនុញ្ញាត",
        "Checked Transactions":"ប្រតិបត្តិការដែលបានពិនិត្យ",
        "Checked Transactions Details":"បានពិនិត្យព័ត៌មានលម្អិតអំពីប្រតិបត្តិការ"
    }
}
