lang = {
    "EN":{
        "home":"Home",
        "ProductName":"Product Name",
        "Weight":"Weight",
        "Price":"Price",
        "Details":"Details",
        "MyProfile":"My Profile",
        "ChangePassword":"Change Password",
        "LogOut":"Log Out",
        "BranchCode":"Branch Code",
        "Department":"Department",
        "UserName":"User Name",
        "Category":"Category",
        "Product":"Product",
        "CreateTransactions":"Create Transactions",
        "ReopenTransactions":"Reopen Transactions",
        "CloseTransactions":"Closed Transactions",
        "CopyRight":"Copyright National Bank of Cambodia. All Rights Reserved",
        "ConsumerPriceIndexSystem":"Consumer Price Index System",
        "Dashboard":"Dashboard"
    },
    "KH":{
        "home":"ផ្ទះ",
        "ProductName":"ឈ្មោះផលិតផល",
        "Weight":"ទំងន់",
        "Price":"តំលៃ",
        "Details":"ព័ត៌មានលម្អិត",
        "MyProfile":"កម្រងព័ត៌មានអ្នកប្រើប្រាស់",
        "ChangePassword":"ផ្លាស់ប្តូរពាក្យសម្ងាត់",
        "LogOut":"ចាកចេញ",
        "BranchCode":"លេខកូដសាខា",
        "Department":"នាយកដ្ឋាន",
        "UserName":"ឈ្មោះ​អ្នកប្រើប្រាស់",
        "Category":"ប្រភេទ",
        "Product":"ផលិតផល",
        "CreateTransactions":"បង្កើតប្រតិបត្តិការ",
        "ReopenTransactions":"បើកប្រតិបត្តិការឡើងវិញ",
        "CloseTransactions":"បិទប្រតិបត្តិការ",
        "CopyRight":"រក្សាសិទ្ធិ ធនាគារជាតិនៃកម្ពុជា រក្សា​រ​សិទ្ធ​គ្រប់យ៉ាង",
        "ConsumerPriceIndexSystem":"ប្រព័ន្ធសន្ទស្សន៍តម្លៃអ្នកប្រើប្រាស់",
        "Dashboard":"ផ្ទាំងគ្រប់គ្រង"
    }
}
