lang = {
    "EN":{
        "home":"Home",
        "ProductName":"Product Name",
        "Weight":"Weight",
        "Price":"Price",
        "Details":"Details",
        "MyProfile":"My Profile",
        "ChangePassword":"Change Password",
        "LogOut":"Log Out",
        "BranchCode":"Branch Code",
        "Department":"Department",
        "UserName":"User Name",
        "Category":"Category",
        "Product":"Product",
        "CreateTransactions":"Create Transactions",
        "ReopenTransactions":"Reopen Transactions",
        "CloseTransactions":"Closed Transactions",
        "CopyRight":"Copyright National Bank of Cambodia. All Rights Reserved",
        "ConsumerPriceIndexSystem":"Consumer Price Index System",
        "Dashboard":"Dashboard",
        "Total":"Total",
        "Submitted":"Submitted",
        "Rejected":"Rejected",
        "Authorized":"Authorized",
        "Reopen":"Reopen",
        "Active":"Active",
        "Deactivated":"Deactivated",
        "Pending":"Pending",
        "Closed":"Closed",
        "Open":"Open",
        "Rejected By Authorizer":"Rejected By Authorizer",
        "Rejected By Checker":"Rejected By Checker",
        "Saved":"Saved",
        "Accepted":"Accepted",
        "InputterNoted":"Inputter Noted",
        "AuthorizerNoted":"Authorizer Noted",
        "CheckerNoted":"Checker Noted",
        "Rice":"Rice", 
        "Shipping":"Shipping", 
        "Transportation":"Transportation", 
        "Ingredients":"Ingredients", 
        "Meat":"Meat", 
        "Fish and Seafood":"Fish and Seafood", 
        "Fruit":"Fruit", 
        "Vegetables":"Vegetables", 
        "Beverages and Tobacco":"Beverages and Tobacco", 
        "Restaurant":"Restaurant", 
        "Clothes and Shoes":"Clothes and Shoes", 
        "Medicine":"Medicine", 
        "Housing":"Housing", 
        "Rice Details":"Rice Details", 
        "Shipping Details":"Shipping Details",
        "Transportation Details":"Transportation Details", 
        "Ingredients Details":"Ingredients Details", 
        "Meat Details":"Meat Details", 
        "Fish and Seafood Details":"Fish and Seafood Details", 
        "Fruit Details":"Fruit Details", 
        "Vegetables Details":"Vegetables Details", 
        "Beverages and Tobacco Details":"Beverages and Tobacco Details", 
        "Restaurant Details":"Restaurant Details", 
        "Clothes and Shoes Details":"Clothes and Shoes Details", 
        "Medicine Details":"Medicine Details", 
        "Housing Details":"Housing Details",
        "Change User Password":"Change User Password",
        "Old Password":"Old Password",
        "Confirm Old Password":"Confirm Old Password",
        "New Password":"New Password",
        "Submit":"Submit",
        "Save":"Save",
        "Clear":"Clear",
        "User Setting":"User Setting",
        "Change Password":"Change Password",
        "Username":"User Name",
        "Role":"Role",
        "Unit":"Unit",
        "Submitter":"Submitter",
        "Submitted Date":"Submitted Date",
        "Inputter":"Inputter",
        "Authorizer":"Authorizer",
        "Checker":"Checker",
        "Administrator":"Administrator",
        "Overview":"Overview",
        "Edit Profile":"Edit Profile",
        "Profile Details":"Profile Details",
        "Full Name":"Full Name",
        "Gender":"Gender",
        "Department":"Department",
        "Position":"Position",
        "Email":"Email",
        "Languages":"Languages",
        "English":"English",
        "Khmer":"Khmer",
        "Female":"Female",
        "Male":"Male",
        "Save Changed":"Save Changed",
        "Submitted Transactions":"Submitted Transactions",
        "Submitted Transactions Management":"Submitted Transactions Management",
        "Transaction Details":"Transaction Details",
        "Transactions History":"Transactions History",
        "Transactions History Management":"Transactions History Management",
        "Status":"Status",
        "Number of Products":"Number of Products",
        "Date":"Date",
        "Food":"Food",
        "Authorized Transactions":"Authorized Transactions",
        "Authorized Transactions Management":"Authorized Transactions Management",
        "Checked Transactions":"Checked Transactions",
        "Checked Transactions Details":"Checked Transactions Details",
        "Users List":"Users List",
        "Create Users":"Create Users",
        "User Management":"User Management",
        "User ID":"User ID",
        "Add New User":"Add New User",
        "Please fill here":"Please fill here",
        "User Default Password is":"User Default Password is",
        "Branch Name":"Branch Name",
        "Refresh":"Refresh",
        "Action":"Action",
        "User Deleted":"User Deleted",
        "Update User":"Update User",
        "Delete User":"Delete User",
        "Reset Password":"Reset Password",
        "Role Management":"Role Management",
        "Create Role":"Create Role",
        "Role ID":"Role ID",
        "Role Name":"Role Name",
        "Role Details":"Role Details",
        "Add New Role":"Add New Role",
        "auto increment":"Auto increment",
        "Update Role":"Update Role",
        "Delete Role":"Delete Role",
        "Add Permission":"Add Permission",
        "Attach Permission":"Attach Permission",
        "Permission of Role":"Permission of Role",
        "Management":"Management",
        "Menu Name":"Menu Name",
        "Link":"Link",
        "Parent":"Parent",
        "Role List":"Role List",
        "View Products":"View Products",
        "Create Category":"Create Category",
        "Category Management":"Category Management",
        "Category ID":"Category ID",
        "Category Code":"Category Code",
        "English Name":"English Name",
        "Khmer Name":"Khmer Name",
        "Add New Category":"Add New Category",
        "Category List":"Category List",
        "Sub Category of":"Sub Category of",
        "Category":"Category",
        "No Sub Category":"No Sub Category",
        "Categories and Products Management":"Categories and Products Management",
        "Update Category":"Update Category",
        "Delete Category":"Delete Category",
        "Add Product to":"Add Product to",
        "Product Code":"ProductCode",
        "Delete Product":"Delete Product",
        "Update Product":"Update Product",
        "Add New Product":"Add New Product",
        "Products List":"Products List",
        "List of Products in":"List of Products in",
        "Update Products of":"Update Products of",
        "Unit in English":"Unit in English",
        "Unit in Khmer":"Unit in Khmer",
        "cannot update":"Cannot Update",
        "Create Product":"Create Product",
        "Create Products of":"Create Products of",
        "Product ID":"Product ID",
        "User Profile":"User Profile",
        "Accepted All Transactions":"Accepted All Transactions",
        "PhoneNumber":"Phone Number",
        "Telegram":"Telegram",
        "Export Transaction":"Export Transaction",
        "Back to Transaction History":"Back to Transaction History",
        "Batch ID":"Batch ID",
        "Base Price":"Base Price",
        "Open Session":"Open Session",
        "Open Session Fro All Branches":"Open Session Fro All Branches",
        "Close Session":"Close Session",
        "Close Session Fro All Branches":"Close Session Fro All Branches",
        "Reopen Session":"Reopen Session",
        "Session":"Session",
        "Session Details":"Session Details",
        "Session Detail Management":"Session Detail Management",
        "Session Duration":"Session Duration",
        "Session Duration Management":"Session Duration Management",
        "Branch Management":"Branch Management",
        "Add New Branch":"Add New Branch",
        "Address":"Address",
        "Update Branch":"Update Branch",
        "Delete Branch":"Delete Branch",
        "View Branches":"View Branches",
        "Create Branch":"Create Branch",
        "Khmer Branch Name":"Khmer Branch Name",
        "English Branch Name":"English Branch Name",
        "Khmer Address":"Khmer Address",
        "English Address":"English Address",
        "Start Session":"Start Session",
        "End Session":"End Session",
        "Batch Name":"Batch Name",
        "Create Date":"Create Date",
        "Create By":"Create By",
        

    },
    "KH":{
        "home":"ផ្ទះ",
        "ProductName":"ឈ្មោះផលិតផល",
        "Weight":"ទំងន់",
        "Price":"តំលៃ",
        "Details":"ព័ត៌មានលម្អិត",
        "MyProfile":"កម្រងព័ត៌មានអ្នកប្រើប្រាស់",
        "ChangePassword":"ផ្លាស់ប្តូរពាក្យសម្ងាត់",
        "LogOut":"ចាកចេញ",
        "BranchCode":"លេខកូដសាខា",
        "Department":"នាយកដ្ឋាន",
        "UserName":"ឈ្មោះ​អ្នកប្រើប្រាស់",
        "Category":"ប្រភេទ",
        "Product":"ផលិតផល",
        "CreateTransactions":"បង្កើតប្រតិបត្តិការ",
        "ReopenTransactions":"បើកប្រតិបត្តិការឡើងវិញ",
        "CloseTransactions":"បិទប្រតិបត្តិការ",
        "CopyRight":"រក្សាសិទ្ធិ ធនាគារជាតិនៃកម្ពុជា រក្សា​រ​សិទ្ធ​គ្រប់យ៉ាង",
        "ConsumerPriceIndexSystem":"ប្រព័ន្ធសន្ទស្សន៍តម្លៃអ្នកប្រើប្រាស់",
        "Dashboard":"ផ្ទាំងគ្រប់គ្រង",
        "Total":"សរុប",
        "Submitted":"បានដាក់ស្នើ",
        "Rejected":"បដិសេធ",
        "Authorized":"អនុញ្ញាត",
        "Reopen":"បើកឡើងវិញ",
        "Active":"ដំណើរការ",
        "Deactivated":"បិទដំណើរការ",
        "Pending":"កំពុងរង់ចាំ",
        "Closed":"បិទ",
        "Open":"បើក",
        "Rejected By Authorizer":"បដិសេធដោយអ្នកផ្តល់សិទ្ធិ",
        "Rejected By Checker":"ច្រានចោលដោយអ្នកពិនិត្យ",
        "Saved":"បានរក្សាទុក",
        "Accepted":"ទទួលយក",
        "InputterNoted":"ព័ត៌មានអ្នកបញ្ចូល",
        "AuthorizerNoted":"ព័ត៌មានអ្នកអនុញ្ញាត",
        "CheckerNoted":"ព័ត៌មានអ្នកពិនិត្យ",
        "Rice":"អង្ករ", 
        "Shipping":"ការដឹកជញ្ជូន", 
        "Transportation":"ការដឹកជញ្ជូន",
        "Ingredients":"គ្រឿងផ្សំ", 
        "Meat":"សាច់", 
        "Fish and Seafood":"ត្រី និងអាហារសមុទ្រ", 
        "Fruit":"ផ្លែឈើ", 
        "Vegetables":"បន្លែ", 
        "Beverages and Tobacco":"ភេសជ្ជៈ និងថ្នាំជក់", 
        "Restaurant":"ភោជនីយដ្ឋាន", 
        "Clothes and Shoes":"សម្លៀកបំពាក់និងស្បែកជើង", 
        "Medicine":"ថ្នាំ", 
        "Housing":"លំនៅដ្ឋាន",
        "Rice Details":"ព័ត៌មានលម្អិតអង្ករ", 
        "Shipping Details":"ព័ត៌មានលម្អិតការដឹកជញ្ជូន", 
        "Transportation Details":"ព័ត៌មានលម្អិតការដឹកជញ្ជូន", 
        "Ingredients Details":"ព័ត៌មានលម្អិតគ្រឿងផ្សំ", 
        "Meat Details":"ព័ត៌មានលម្អិតសាច់", 
        "Fish and Seafood Details":"ព័ត៌មានលម្អិតត្រី និងអាហារសមុទ្រ", 
        "Fruit Details":"ព័ត៌មានលម្អិតផ្លែឈើ", 
        "Vegetables Details":"ព័ត៌មានលម្អិតបន្លែ", 
        "Beverages and Tobacco Details":"ព័ត៌មានលម្អិតភេសជ្ជៈ និងថ្នាំជក់", 
        "Restaurant Details":"ព័ត៌មានលម្អិតភោជនីយដ្ឋាន", 
        "Clothes and Shoes Details":"ព័ត៌មានលម្អិតសម្លៀកបំពាក់និងស្បែកជើង", 
        "Medicine Details":"ព័ត៌មានលម្អិតថ្នាំ", 
        "Housing Details":"ព័ត៌មានលម្អិតលំនៅដ្ឋាន",  
        "Change User Password":"ផ្លាស់ប្តូរពាក្យសម្ងាត់អ្នកប្រើប្រាស់",
        "Old Password":"លេខសំងាត់​ចាស់",
        "Confirm Old Password":"បញ្ជាក់ពាក្យសម្ងាត់ចាស់",
        "New Password":"ពាក្យសម្ងាត់​ថ្មី",
        "Submit":"ដាក់ស្នើ",
        "Save":"រក្សាទុក",
        "Clear":"សំអាត",
        "User Setting":"ការកំណត់អ្នកប្រើប្រាស់",
        "Change Password":"ផ្លាស់ប្តូរពាក្យសម្ងាត់",
        "User Profile":"កម្រងព័ត៌មានអ្នកប្រើប្រាស់",
        "Username":"ឈ្មោះ​អ្នកប្រើប្រាស់",
        "Role":"តួនាទី",
        "Unit":"ឯកតា",
        "Inputter":"អ្នកបញ្ចូល",
        "Authorizer":"អ្នកអនុញ្ញាត",
        "Checker":"អ្នកត្រួតពិនិត្យ",
        "Administrator":"អ្នកគ្រប់គ្រង",
        "Overview":"ទិដ្ឋភាពទូទៅ",
        "Edit Profile":"កែសម្រួលប្រវត្តិរូប",
        "Profile Details":"ព័ត៌មានលំអិតអំពីប្រវត្តិរូប",
        "Full Name":"ឈ្មោះ​ពេញ",
        "Gender":"ភេទ",
        "Position":"មុខតំណែង",
        "Email":"អ៊ីមែល",
        "Languages":"ភាសា",
        "English":"ភាសាអង់គ្លេស",
        "Khmer":"ភាសាខ្មែរ",
        "Female":"ស្រី",
        "Male":"ប្រុស",
        "Save Changed":"រក្សាទុកបានផ្លាស់ប្តូរ",
        "Submitted Transactions":"ប្រតិបត្តិការដែលបានដាក់ស្នើ",
        "Submitted Transactions Management":"ការគ្រប់គ្រងប្រតិបត្តិការដែលបានបញ្ជូន",
        "Transaction Details":"ព័ត៌មានលម្អិតអំពីប្រតិបត្តិការ",
        "Transactions History":"ប្រវត្តិប្រតិបត្តិការ",
        "Transactions History Management":"ការគ្រប់គ្រងប្រវត្តិប្រតិបត្តិការ",
        "Status":"ស្ថានភាព",
        "Number of Products":"ចំនួនផលិតផល",
        "Date":"កាលបរិច្ឆេទ",
        "Food":"អាហារ",
        "Authorized Transactions":"ប្រតិបត្តិការដែលមានការអនុញ្ញាត",
        "Authorized Transactions Management":"ការគ្រប់គ្រងប្រតិបត្តិការដែលមានការអនុញ្ញាត",
        "Checked Transactions":"ប្រតិបត្តិការដែលបានពិនិត្យ",
        "Checked Transactions Details":"បានពិនិត្យព័ត៌មានលម្អិតអំពីប្រតិបត្តិការ",
        "Users List":"បញ្ជីអ្នកប្រើប្រាស់",
        "Create Users":"បង្កើតអ្នកប្រើប្រាស់",
        "User Management":"ការគ្រប់គ្រងអ្នកប្រើប្រាស់",
        "User ID":"លេខ​សម្គាល់​អ្នក​ប្រើ",
        "Add New User":"បង្កើតអ្នកប្រើប្រាស់ថ្មី",
        "Please fill here":"សូមបំពេញនៅទីនេះ",
        "User Default Password is":"ពាក្យសម្ងាត់លំនាំដើមអ្នកប្រើប្រាស់គឺ",
        "Branch Name":"ឈ្មោះសាខា",
        "Refresh":"ផ្ទុកឡើងវិញ",
        "Action":"សកម្មភាព",
        "User Deleted":"អ្នកប្រើប្រាស់ត្រូវបានលុប",
        "Update User":"ធ្វើបច្ចុប្បន្នភាពអ្នកប្រើប្រាស់",
        "Delete User":"លុបអ្នកប្រើប្រាស់",
        "Reset Password":"កំណត់ពាក្យសម្ងាត់ឡើងវិញ",
        "Role Management":"ការគ្រប់គ្រងតួនាទី",
        "Create Role":"បង្កើតតួនាទី",
        "Role ID":"លេខសម្គាល់តួនាទី",
        "Role Name":"ឈ្មោះតួនាទី",
        "Role Details":"ព័ត៌មានលម្អិតអំពីតួនាទី",
        "Add New Role":"បន្ថែមតួនាទីថ្មី",
        "auto increment":"ការបង្កើនដោយស្វ័យប្រវត្តិ",
        "Update Role":"ធ្វើបច្ចុប្បន្នភាពតួនាទី",
        "Delete Role":"លុបតួនាទី",
        "Add Permission":"បន្ថែមការអនុញ្ញាត",
        "Attach Permission":"ភ្ជាប់ការអនុញ្ញាត",
        "Permission of Role":"ការអនុញ្ញាតពីតួនាទី",
        "Management":"ការគ្រប់គ្រង",
        "Menu Name":"ឈ្មោះម៉ឺនុយ",
        "Link":"តំណភ្ជាប់",
        "Parent":"ជាចម្បង",
        "Role List":"បញ្ជីតួនាទី",
        "View Products":"មើលផលិតផល",
        "Create Category":"បង្កើតប្រភេទ",
        "Category Management":"ការគ្រប់គ្រងប្រភេទ",
        "Category ID":"លេខសម្គាល់ប្រភេទ",
        "Category Code":"លេខកូដប្រភេទ",
        "English Name":"ឈ្មោះភាសាអង់គ្លេស",
        "Khmer Name":"ឈ្មោះភាសាខ្មែរ",
        "Add New Category":"បន្ថែមប្រភេទថ្មី",
        "Category List":"បញ្ជីប្រភេទ",
        "Sub Category of":"ប្រភេទរងនៃ",
        "Category":"ប្រភេទ",
        "No Sub Category":"មិនមានប្រភេទរងទេ",
        "Categories and Products Management":"ប្រភេទ និងការគ្រប់គ្រងផលិតផល",
        "Update Category":"ធ្វើបច្ចុប្បន្នភាពប្រភេទ",
        "Delete Category":"លុប​ប្រភេទ",
        "Add Product to":"បន្ថែមផលិតផលទៅ",
        "Product Code":"លេខកូដផលិតផល",
        "Delete Product":"លុបផលិតផល",
        "Update Product":"ធ្វើបច្ចុប្បន្នភាពផលិតផល",
        "Add New Product":"បន្ថែមផលិតផលថ្មី",
        "Products List":"បញ្ជីផលិតផល",
        "List of Products in":"បញ្ជីផលិតផលនៅក្នុង",
        "Update Products of":"ធ្វើឱ្យទាន់សម័យផលិតផលរបស់",
        "Unit in English":"ឯកតាជាភាសាអង់គ្លេស",
        "Unit in Khmer":"ឯកតាជាភាសាខ្មែរ",
        "cannot update":"មិនអាចធ្វើបច្ចុប្បន្នភាពបានទេ",
        "Create Product":"បង្កើតផលិតផល",
        "Create Products of":"បង្កើតផលិតផលរបស់",
        "Product ID":"លេខសម្គាល់ផលិតផល",
        "Accepted All Transactions":"ទទួលយករាល់ប្រតិបត្តិការទាំងអស់",
        "PhoneNumber":"លេខទូរសព្ទ",
        "Telegram":"តេឡេក្រាម",
        "Export Transaction":"ទាញយកប្រតិបត្តិ",
        "Back to Transaction History":"ត្រឡប់ទៅ ប្រវត្តិប្រតិបត្តិការ",
        "Batch ID":"លេខសម្គាល់បាច់",
        "Submitter":"អ្នកដាក់ស្នើ",
        "Submitted Date":"កាលបរិច្ឆេទដែលបានដាក់ស្នើ",
        "Base Price":"តម្លៃមូលដ្ឋាន",
        "Open Session":"បើករយៈពេល",
        "Close Session":"បិទរយៈពេល",
        "Open Session Fro All Branches":"បើកវគ្គសម្រាប់គ្រប់សាខា",
        "Close Session Fro All Branches":"បិទវគ្គសម្រាប់គ្រប់សាខា",
        "Reopen Session":"បើករយៈពេលឡើងវិញ",
        "Session":"រយៈពេល",
        "Session Details":"រយៈពេលលំអិត",
        "Session Detail Management":"ការគ្រប់គ្រងរយៈពេលលំអិត",
        "Session Duration":"ពេលវេលារយៈពេល",
        "Branch Management":"ការគ្រប់គ្រងសាខា",
        "Add New Branch":"បន្ថែមសាខាថ្មី",
        "Address":"អាស័យដ្ឋាន",
        "Update Branch":"ធ្វើបច្ចុប្បន្នភាពសាខា",
        "Delete Branch":"លុបសាខា",
        "View Branches":"មើលសាខា",
        "Create Branch":"បង្កើតសាខា",
        "Khmer Branch Name":"ឈ្មោះសាខាខ្មែរ",
        "English Branch Name":"ឈ្មោះសាខាភាសាអង់គ្លេស",
        "Khmer Address":"អាស័យដ្ឋានខ្មែរ",
        "English Address":"អាសយដ្ឋានភាសាអង់គ្លេស",
        "Session Duration Management":"ការគ្រប់គ្រងពេលវេលារយៈពេល",
        "Start Session":"បើករយៈពេល",
        "End Session":"បិទរយៈពេល",
        "Batch Name":"ឈ្មោះបាច់",
        "Create Date":"បង្កើតកាលបរិច្ឆេទ",
        "Create By":"បង្កើតដោយ",
    }
}
